input_file: sequences.fasta
protocol: sequence_to_value
model_choice: FNN
optimizer_choice: adam
loss_choice: mean_squared_error
num_epochs: 200
use_class_weights: False
learning_rate: 1e-3
batch_size: 128
device: cpu
embedder_name: AAOntology