input_file: sequences.fasta
protocol: residues_to_class
model_choice: LightAttention
optimizer_choice: adam
loss_choice: cross_entropy_loss
num_epochs: 200
use_class_weights: False
learning_rate: 1e-3
batch_size: 128
disable_pytorch_compile: False
embedder_name: one_hot_encoding