input_file: sequences.fasta
protocol: sequence_to_class
model_choice: FNN
optimizer_choice: adam
loss_choice: cross_entropy_loss
num_epochs: 200
use_class_weights: True
learning_rate: 1e-3
batch_size: 128
save_split_ids: False
use_half_precision: True
device: cuda
disable_pytorch_compile: True
embedder_name: Rostlab/prot_t5_xl_uniref50
dimension_reduction_method: pca
n_reduced_components: 30